### ISSUE TITLE
sqlanydb.connect() behavior in with statement

### ISSUE THREAD

**Issue by jysue** [sqlanywhere/sqlanydb#8]
When I connect explicitly, conn = sqlanydb.connect(), type(conn) is <class 'sqlanydb.Connection'>.

If I have the connect in a with statement, with sqlanydb.connect() as conn:
type(conn) is <class 'sqlanydb.Cursor'>.

Is this the intended effect? I can live with this.
[testsqlanywith.pdf](https://github.com/sqlanywhere/sqlanydb/files/852815/testsqlanywith.pdf)

Thank you,
Jeffrey Sue

**Comment by gperrow-SAP** [comment]
Yes, this is intended behaviour. The idea is for something like:

    with sqlanydb.connect( ... ) as c:
       c.execute( 'insert into mytable...' )

This is a quick way to create a connection and execute a single statement. We automatically commit the statement if it succeeds and rollback if an exception occurs.

**Comment by jysue** [comment]
Thank you for the quick answer.

**Comment by gperrow-SAP** [comment]
My apologies, I've found that this is _not_ expected behaviour. With the example I gave above, the insert will work and be committed, but the connection will not be closed when you expect it to be. Something like this will work:

    conn = sqlanydb.connect( ... )
    with conn as c:
        c.execute( 'insert into mytable...' )
    conn.close()

But this seems odd. It would make more sense to me to support:

    with sqlanydb.connect( ... ) as conn:
        curs = conn.cursor()
        curs.execute( 'insert into mytable...' )
        curs.close()
        # Other things using conn

Where the connection is closed at the end of the `with` statement. Let me know if I've misunderstood something, but it seems to me that the second example above would be the more intuitive behaviour.

**Comment by gperrow-SAP** [comment]
After some more research, I've found that there is no "standard" for how a database API module should handle the `with` statement. The behaviour we've implemented (which I said was "_not_ expected behaviour" above) is the "usual" behaviour according to [this Stack Overflow answer](http://stackoverflow.com/a/15568275/1821). Given this, and given the fact that this is how our driver is _currently_ implemented, I think it would be safer to leave the behaviour as-is rather than risk breaking existing applications that use this behaviour. Sorry for the confusion.

**Comment by jysue** [comment]
Thank you for researching. The Stack Overflow answer makes a lot of sense.

Thank you,
Jeffrey Sue

**Comment by jysue** [comment]
I think I understand more now. Looking at the source for sqlanydb, particularly the Connection methods __enter__ and __exit__, the use of with is supposed to be only for transactions, and not for closing connections or cursors. Sqlanydb follows this Stack Overflow answer <http://stackoverflow.com/questions/5669878/when-to-close-cursors-using-mysqldb/22618781#22618781> and section 8.1 of What’s New in Python 2.5 <http://pys60.garage.maemo.org/doc/whatsnew/pep-343.html>. 

Thanks again.
